name: src
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.0.0
  pin_code_fields: ^7.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  theme_provider: ^0.5.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  modal_bottom_sheet: ^2.0.0
  image_picker: ^0.8.3+3
  shared_preferences: ^2.0.7
  photo_view: ^0.13.0
  skeleton_text: ^3.0.0
  provider: ^6.0.0
  mask_text_input_formatter: ^2.0.0
  curved_navigation_bar: 1.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  jiffy: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/svg/icon/
    - assets/svg/
    - assets/logo/
    - assets/gif/
    - assets/image/
  fonts:
    - family: Roboto Condensed
      fonts:
        - asset: assets/font/RobotoCondensed-Regular.ttf
        - asset: assets/font/RobotoCondensed-Bold.ttf
        - asset: assets/font/RobotoCondensed-BoldItalic.ttf
        - asset: assets/font/RobotoCondensed-Italic.ttf
        - asset: assets/font/RobotoCondensed-Light.ttf
        - asset: assets/font/RobotoCondensed-LightItalic.ttf
  uses-material-design: true
flutter_intl: # Add this line
  enabled: true # Add this line
  class_name: S # Add this line
  main_locale: vi # Add this line
  arb_dir: lib/commons/l10n/translation # Add this line
  output_dir: lib/commons/l10n/generated # Add this line
